[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "solidity-bytes-utils/=lib/solidity-bytes-utils",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    "@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol",
    "@layerzerolabs/test-devtools-evm-foundry/=lib/devtools/packages/test-devtools-evm-foundry",
]
