# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: salviensky@gmail.com
author_name: Simon Samuel
contract_name: agence_factory
deployment_language: python
preset_name: starter
project_name: algorand

