[workspace]
members = [
    "agence_factory",
    "agence_gigs",
    "agence_governance",
    "agence_staking",
]
resolver = "2"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
