build-dao:
	@cd dao && ./scripts/build.sh

build-gigs:
	@cd gigs && ./scripts/build.sh

build-staking:
	@cd staking && ./scripts/build.sh

build-governance:
	@cd governance && ./scripts/build.sh

build: build-dao build-gigs build-staking build-governance


